# Generated by Django 5.0.4 on 2024-05-02 19:04

from django.db import migrations, models

import postgresql_geometry.django.models.fields
from postgresql_geometry.django.models.operations import CubeExtension, EarthDistanceExtension


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        CubeExtension(),
        EarthDistanceExtension(),
        migrations.CreateModel(
            name="Store",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("location", postgresql_geometry.django.models.fields.PointField()),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("location", postgresql_geometry.django.models.fields.PointField(null=True)),
            ],
        ),
    ]
